# -----------------------------------------------------------------------------
# Application Configuration
# -----------------------------------------------------------------------------
tz: "Asia/Jakarta"

server:
  address:
    http: "0.0.0.0:8080"

# -----------------------------------------------------------------------------
# Modules Configuration
# -----------------------------------------------------------------------------
modules:
  flip:
    enabled: true
